import { PlayerColor } from "@/types";

export interface ColorTheme {
  name: PlayerColor;
  label: { en: string; fa: string };
  swatch: string; // hex for the swatch circle
  bg: string; // page background
  bgMuted: string; // subtle card backgrounds
  bgStrong: string; // strong accent bg
  text: string; // primary text on bg
  textMuted: string; // secondary text
  textOnStrong: string; // text on bgStrong
  border: string; // border color
  ring: string; // focus ring
  button: string; // primary button classes
  buttonHover: string;
  wave1: string; // wave fill colors (hex)
  wave2: string;
  wave3: string;
}

export const COLOR_THEMES: Record<PlayerColor, ColorTheme> = {
  blue: {
    name: "blue",
    label: { en: "Blue", fa: "آبی" },
    swatch: "#3b82f6",
    bg: "bg-sky-950",
    bgMuted: "bg-sky-900/60",
    bgStrong: "bg-sky-500",
    text: "text-sky-50",
    textMuted: "text-sky-300",
    textOnStrong: "text-white",
    border: "border-sky-700",
    ring: "ring-sky-400",
    button: "bg-sky-500 text-white",
    buttonHover: "hover:bg-sky-400",
    wave1: "#0c4a6e",
    wave2: "#075985",
    wave3: "#0369a1",
  },
  purple: {
    name: "purple",
    label: { en: "Purple", fa: "بنفش" },
    swatch: "#8b5cf6",
    bg: "bg-violet-950",
    bgMuted: "bg-violet-900/60",
    bgStrong: "bg-violet-500",
    text: "text-violet-50",
    textMuted: "text-violet-300",
    textOnStrong: "text-white",
    border: "border-violet-700",
    ring: "ring-violet-400",
    button: "bg-violet-500 text-white",
    buttonHover: "hover:bg-violet-400",
    wave1: "#2e1065",
    wave2: "#3b0764",
    wave3: "#4c1d95",
  },
  brown: {
    name: "brown",
    label: { en: "Brown", fa: "قهوه‌ای" },
    swatch: "#92400e",
    bg: "bg-stone-900",
    bgMuted: "bg-stone-800/60",
    bgStrong: "bg-amber-800",
    text: "text-stone-50",
    textMuted: "text-stone-300",
    textOnStrong: "text-white",
    border: "border-stone-600",
    ring: "ring-amber-600",
    button: "bg-amber-800 text-white",
    buttonHover: "hover:bg-amber-700",
    wave1: "#1c1917",
    wave2: "#292524",
    wave3: "#44403c",
  },
  green: {
    name: "green",
    label: { en: "Green", fa: "سبز" },
    swatch: "#059669",
    bg: "bg-emerald-950",
    bgMuted: "bg-emerald-900/60",
    bgStrong: "bg-emerald-600",
    text: "text-emerald-50",
    textMuted: "text-emerald-300",
    textOnStrong: "text-white",
    border: "border-emerald-700",
    ring: "ring-emerald-400",
    button: "bg-emerald-600 text-white",
    buttonHover: "hover:bg-emerald-500",
    wave1: "#022c22",
    wave2: "#064e3b",
    wave3: "#065f46",
  },
  red: {
    name: "red",
    label: { en: "Red", fa: "قرمز" },
    swatch: "#f43f5e",
    bg: "bg-rose-950",
    bgMuted: "bg-rose-900/60",
    bgStrong: "bg-rose-500",
    text: "text-rose-50",
    textMuted: "text-rose-300",
    textOnStrong: "text-white",
    border: "border-rose-700",
    ring: "ring-rose-400",
    button: "bg-rose-500 text-white",
    buttonHover: "hover:bg-rose-400",
    wave1: "#4c0519",
    wave2: "#881337",
    wave3: "#9f1239",
  },
  yellow: {
    name: "yellow",
    label: { en: "Yellow", fa: "زرد" },
    swatch: "#d97706",
    bg: "bg-amber-950",
    bgMuted: "bg-amber-900/60",
    bgStrong: "bg-amber-500",
    text: "text-amber-50",
    textMuted: "text-amber-300",
    textOnStrong: "text-white",
    border: "border-amber-700",
    ring: "ring-amber-400",
    button: "bg-amber-500 text-white",
    buttonHover: "hover:bg-amber-400",
    wave1: "#451a03",
    wave2: "#78350f",
    wave3: "#92400e",
  },
  pink: {
    name: "pink",
    label: { en: "Pink", fa: "صورتی" },
    swatch: "#ec4899",
    bg: "bg-pink-950",
    bgMuted: "bg-pink-900/60",
    bgStrong: "bg-pink-400",
    text: "text-pink-50",
    textMuted: "text-pink-300",
    textOnStrong: "text-white",
    border: "border-pink-700",
    ring: "ring-pink-400",
    button: "bg-pink-400 text-white",
    buttonHover: "hover:bg-pink-300",
    wave1: "#500724",
    wave2: "#831843",
    wave3: "#9d174d",
  },
  orange: {
    name: "orange",
    label: { en: "Orange", fa: "نارنجی" },
    swatch: "#f97316",
    bg: "bg-orange-950",
    bgMuted: "bg-orange-900/60",
    bgStrong: "bg-orange-500",
    text: "text-orange-50",
    textMuted: "text-orange-300",
    textOnStrong: "text-white",
    border: "border-orange-700",
    ring: "ring-orange-400",
    button: "bg-orange-500 text-white",
    buttonHover: "hover:bg-orange-400",
    wave1: "#431407",
    wave2: "#7c2d12",
    wave3: "#9a3412",
  },
};

export const DEFAULT_THEME: ColorTheme = {
  name: "blue",
  label: { en: "Default", fa: "پیش‌فرض" },
  swatch: "#6366f1",
  bg: "bg-slate-950",
  bgMuted: "bg-slate-900/60",
  bgStrong: "bg-indigo-600",
  text: "text-slate-50",
  textMuted: "text-slate-400",
  textOnStrong: "text-white",
  border: "border-slate-700",
  ring: "ring-indigo-400",
  button: "bg-indigo-600 text-white",
  buttonHover: "hover:bg-indigo-500",
  wave1: "#0f172a",
  wave2: "#1e1b4b",
  wave3: "#1e293b",
};
